qmhc/vite-plugin-dts

- src/compile.ts
- src/index.ts
for .vue template file:
```
<script lang="tsx">
...
</script>
```
`transform(code, id)` generated `.js` source id, but source file should be `.tsx/.jsx`.
this pull request fix it.
> fix vue template tsx/jsx script id.

- example/vite.config.ts
- src/plugin.ts
Add `aliasesExclude` configuration to control not transforming aliases path.
> feat: add `aliasesExclude` configuration

- src/plugin.ts
修复如果入口文件不存在 export default object; 形式的导出 那么在生成.d.ts文件的时候就会报
Error: Internal Error: Unable to analyze the export "default" in
D:/learn-project/vite-plugin-dts-main/example/types/src/index.d.ts 的错误
Fixes https://github.com/qmhc/vite-plugin-dts/issues/69
> 修复如果入口文件不存在 export default object; 形式的导出 那么在生成.d.ts文件报错问题

- src/plugin.ts
@qmhc  Hi，I try to use aliasesExclude to exclude specified import paths when transform aliases，but not work. So I try to fix it
related issues：https://github.com/qmhc/vite-plugin-dts/issues/73
> fix: aliasesExclude not work

- src/plugin.ts
> fix: get the `include` and `exclude` fields from the parent config

- src/compile.ts
Hi, in vue 2.6x project, the compiler get a wrong address resolution from global node_modules but not from my project.
case:
project: vue@2.6.14
global: vue@2.7.13
It will get the global node_modules(`${global}/node_modules/vue/compiler-sfc`) , not from my project node_modules(`${project}/node_modules/@vue/compiler-sfc`)
> fix: incorrect compiler address resolution

- package.json
Hi! I noticed that in my project, TypeScript cannot infer the types of this plugin.
But if you add the `types` export, it starts to work.
> Note that the `types` export **has** to be the first entry in an exports object
My typescript config for reference:
```json
{
"$schema": "https://json.schemastore.org/tsconfig",
"display": "base",
"compileOnSave": false,
"compilerOptions": {
"composite": false,
"target": "es2020",
"module": "es2022",
"lib": ["es2022", "dom"],
"sourceMap": true,
"declaration": true,
"declarationMap": true,
"noUnusedLocals": false,
"moduleResolution": "nodenext",
"esModuleInterop": true,
"allowSyntheticDefaultImports": true,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"importHelpers": true,
"inlineSources": false,
"isolatedModules": true, …
```
> fix: add types export to package.json

- src/compile.ts
项目中使用了装饰器，发现会报错
```
[vite:dts] This experimental syntax requires enabling one of the following parser plugin(s): "decorators", "decorators-legacy".
```
对比 `@vue/compiler-sfc` 和上面处理  script setup 的部分发现是漏了 `decorators-legacy`，补上后解决问题
> fix: compilation missing plugin "decorators-legacy"

- build.config.ts
Mark `typescript` as an external dependency, so that it doesn't end up in the bundled code.
|before|after|
|--|--|
| ![image](https://user-images.githubusercontent.com/6443113/209136780-bca803ff-61cf-4423-9bb7-0ba535ab1ddd.png) |  ![image](https://user-images.githubusercontent.com/6443113/209136815-c3abb709-6b10-405b-94e2-1aa896743be0.png) |
> fix: mark typescript as external dependency

- package.json
- pnpm-lock.yaml
I just want to be able to use the new keyword `satisfies` which should be working with `ts-morph` @17.0.1 if that's okay with you? Not sure if anything else is required here?
> chore: update ts-morph@17.0.1

- src/plugin.ts
支持从 `package.json` 文件中的 `publishConfig.types` 字段来获取路径
https://pnpm.io/zh/package_json#publishconfig
> fix: insertTypesEntry config supports publishConfig.types

- src/plugin.ts
I added small change so that it will be compatible with Svelte Frameworks.
It will look for .svelte files and create declaration file that looks like
```
export { SvelteComponentTyped as default } from 'svelte/internal';
```
> feat: compatible with svelte

- README.md
- README.zh-CN.md
- examples/ts/vite.config.ts
- src/plugin.ts
- src/types.ts
过去输出dts同时会输出其他js产物
现在支持仅输出dts文件
> feat: support only output dts

- src/plugin.ts
resolves #259 
I found that #259 happens after https://github.com/qmhc/vite-plugin-dts/commit/284c77ff65741f2cddbca3eba380b4a624cec3c7.
I just restored this change from the latest (63321c2be82f02b543ec17460133b00d209fffd3),
which makes it generate `.map` files for `.d.ts` files well (checked on bac2a7d3b1fec753706c35b2681163690ecaec81).
and It seems #254 is not reproduced 🤔(checked on b041a4c).
> fix: fails to generate declarationMaps

- README.md
- README.zh-CN.md
- src/types.ts
Noticed this when copying from doc to use the exclude option.
> fix: minor typo in docs

- src/rollup.ts
Support was missing in this particular regex.
> fix: support module prefix

- src/plugin.ts
- src/utils.ts
该 PR 修复 Monorepo 项目中 vite-plugin-dts 对 TypeScript 依赖库路径获取的问题。
Monorepo 项目的 Workspace Root 安装 TS 版本为 `v5.5.4`，在子项目中 vite-plugin-dts 没有正确获取 Workspace Root 的 TS（通过 debug 观察 libFolder 变量值为 `undefined`），而它使用了 `api-extractor` 内置的 TS `v5.4.2` 版本，如图：
可能相关的 ISSUE：https://github.com/qmhc/vite-plugin-dts/issues/266
Monorepo 项目，如果 `<WorkspaceRoot>/node_modules/typescript` 存在，但子项目 `<WorkspaceRoot>/packages/xxx/node_modules/typescript` 不存在。
1. 创建 Monorepo 并初始化 Node 子项目
2. 在 Workspace Root 安装 typescript v5.5.4 (`pnpm add -D --workspace-root typescript`)
3. 执行子项目的编译（`pnpm -F vite-project build`）
https://github.com/qwqcode/vite-plugin-dts-mre
clone 后给 node_modules 中的相关代码打上断点，通过 VSCode JS 调试终端执行 `pnpm build`
生成 dts 文件调用 `@microsoft/api-extractor` 的 `Extractor.invoke` 方法会传递 …
> fix: typescript lib path resolution for api-extractor in monorepo

- src/utils.ts
- tests/utils.spec.ts
本 PR 补充修复 #360 中新增的 `getTsLibFolder` 函数在 Win 环境下出现不符合预期的问题。
**预期结果** (末尾不包含 `/lib/typescript.js`)：
```
'node_modules/.pnpm/typescript@5.5.4/node_modules/typescript'
```
**错误结果**：
```
'node_modules/.pnpm/typescript@5.5.4/node_modules/typescript/lib/typescript.js'
```
在 Windows 环境下，由于路径分隔符斜杠和 Unix 环境不同，`require.resolve('typescript')` 返回结果需要做 `normalizePath` 处理，这样才能始终正确地 replace 去掉末尾的 `/lib/typescript.js`。
https://github.com/qmhc/vite-plugin-dts/pull/360#issuecomment-2277836720
> fix: normalize typescript lib path for rollup

- src/utils.ts
- tests/transform.spec.ts
- tests/utils.spec.ts
With a path alias like `@/*` pointing to `src/*`, an import like this:
an import statement like `import { foo } from '@/foo'`
transforms to `import { foo } from './src/foo'`
There is an issue, however, with nested imports being ignored:
an import like `import { foo } from '@/nested/foo'`
should transformed to `import { foo } from './src/nested/foo'`
but actually just stays as `import { foo } from '@/nested/foo'`
The fix was to update the regex pattern to look for *anything* in place of the asterisk (`(.+)`) rather than just 'any non forward slash' (`([^\\/]+)`).
https://github.com/qmhc/vite-plugin-dts/blob/8a0c1406a97e217c1ccdfc0addf69351294eb934/src/utils.ts#L444-L446
The commit log tells the story best and that's probably the easiest way to review the PR as well:
- **test(transform): …
> Fix issue with nested imports

- examples/react/src/components/HelloWorld.tsx
- examples/react/src/hooks/useCount.ts
- examples/react/src/index.ts
- examples/react/tsconfig.json
- src/plugin.ts
- src/utils.ts
- tests/utils.spec.ts
Fixes https://github.com/qmhc/vite-plugin-dts/issues/346
> feat: add support for configDir

- src/plugin.ts
vite use format and entry to generate fileName
keep the same with vite
> fix: use entry name instead of entry path to generate indexName
